export const images = {
  logo: "/images/logo.png",
  profile: "/images/profile.jpeg",
  heroIllustration: "/images/heroIllustration.png",
  evilEye: "/images/evilEye.png",
  ganeshcat: "/images/ganeshcat.png",
  lemon: "/images/lemon.png",
  hamsahand: "/images/hamsahand.png",
  gvm: "/images/gvm.png",
  bananaCat: "/images/bananacat.png",
  vanakam: "/images/vanakam.png",
  kaipulla: "/images/kaipulla.png",
  vijay: "/images/vijay.png",
  anger: "/images/anger.png",
  stepimg1: "/images/stepimg1.png",
  stepimg2: "/images/stepimg2.png",
  stepimg3: "/images/stepimg3.png",
  hangimg: "/images/hangimg.png",
  illustration: "/images/illustration.png",
} as const;
